auth-server:
  url: ${UAA_URL}
  trust_store: /app/stores/trust_store.jks
  trust_store_password: ${TRUST_STORE_PASSWORD}

encryption:
  key_creation_enabled: true
  providers:
    - provider_name: int
      provider_type: internal
      keys:
        - active: true
          encryption_password: ${ENCRYPTION_PASSWORD}

security:
  authorization:
    acls:
      enabled: true
    permissions:
      - actors:
          - "uaa-client:credhub_client"
          - "uaa-user:66e087aa-b6e2-4e98-b699-a0c17f175b27"
        operations:
          - read
          - write
          - delete
          - read_acl
          - write_acl
        path: "/*"
  oauth2:
    resource:
      id: credhub
    enabled: true

server:
  port: 9000
  ssl:
    enabled: true
    key_store: /app/stores/key_store.jks
    key_store_password: ${KEY_STORE_PASSWORD}
    key_password: ${KEY_STORE_PASSWORD}
    key_alias: cert
    ciphers: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    client_auth: want
    trust_store: /app/stores/trust_store.jks
    trust_store_password: ${TRUST_STORE_PASSWORD}
    trust_store_type: JKS
    enabled-protocols: TLSv1.2

spring:
  flyway:
    enabled: true
    locations:
      - classpath:/db/migration/common
      - classpath:/db/migration/h2
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: admin
    url: jdbc:h2:~/test
  profiles:
    active: prod

certificates:
  concatenate_cas: true
  enable_default_ca_key_usages: ${ENABLE_DEFAULT_CA_KEY_USAGES}
