auth-server:
  url: https://50.17.59.67:8443

encryption:
  provider: dev_internal
  active-key: D673ACD01DA091B08144FBC8C0B5F524

spring:
  datasource:
    # postgres/h2
    username: pivotal
    # mysql
#    username: root
    password:
#    url: jdbc:postgresql://localhost:5432/credhub
#    url: jdbc:mysql://localhost:3306/credhub

flyway:
  # last value is either postgres/h2/mysql
  locations: classpath:/db/migration/common,classpath:/db/migration/h2

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsKxPDE3VJx5yTU6TMEad
          KYxXCeRDdc2ctc0Ke0FxMkcKNG4CPwF39+lAOd+jwNlDFcH7vxeyYrtANNd/gFAU
          W7yqESfhdkB0whcStSRuevll6/3xy54bg1+cHicEl4dbvMaF+mx3MJoImn8rLOJy
          heYyftATUxfyf3Uoo5minTCAh2SppnmYGpWz8OltKuTFP809vxOO4Ah4dgMcx8Yk
          ePrU0sQoP+C3sdiyBYZSf+G01eeFaawr1NUtRpT/htS/tgFReYIFrox4CSZx7SsX
          KIlFvmT8XstT2JndP0iiZdod9V+h6FgowfExdWlNyUl/aWVGtmVftOQLZsSMtrHR
          xwIDAQAB
          -----END PUBLIC KEY-----

server:
  port: 9000
